# Generated by Django 5.1.7 on 2026-07-21 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total_contado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='sales.arqueoturno')),
            ],
        ),
        migrations.CreateModel(
            name='Boveda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boveda', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.sucursal')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='core.sucursal')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='sales.listaprecio')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventory.productovariante')),
            ],
            options={
                'ordering': ['variante'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO_CAJERO', 'Cerrado por Cajero'), ('CERRADO_SUPERVISOR', 'Cerrado por Supervisor'), ('AUDITADO', 'Auditado')], default='ABIERTO', max_length=30)),
                ('abierto_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='sales.caja')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arqueoturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='sales.turnocaja'),
        ),
        migrations.CreateModel(
            name='TurnoCajaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('desasignado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ajuste_redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.DateTimeField(blank=True, null=True)),
                ('anulada', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('RETIRO_BOVEDA', 'Retiro a Bóveda'), ('INGRESO', 'Ingreso Manual'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=30)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR')], max_length=20, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hash_integridad', models.CharField(editable=False, max_length=64)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sales.turnocaja')),
                ('referencia_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, default='', max_length=300)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('talla', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_tela', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['sucursal', 'activa'], name='sales_caja_sucursa_828b7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='unique_caja_codigo_por_sucursal'),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['sucursal', 'activa'], name='sales_lista_sucursa_49d1b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='listaprecio',
            constraint=models.UniqueConstraint(fields=('sucursal', 'tipo_venta'), name='unique_lista_por_sucursal_tipo'),
        ),
        migrations.AddIndex(
            model_name='preciovariante',
            index=models.Index(fields=['lista'], name='sales_preci_lista_i_254c05_idx'),
        ),
        migrations.AddIndex(
            model_name='preciovariante',
            index=models.Index(fields=['variante'], name='sales_preci_variant_517596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preciovariante',
            unique_together={('variante', 'lista')},
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('caja',), name='unique_turno_abierto_por_caja'),
        ),
        migrations.AddIndex(
            model_name='turnocajausuario',
            index=models.Index(fields=['activo'], name='sales_turno_activo_4f2676_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnocajausuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('turno', 'usuario'), name='unique_usuario_activo_por_turno'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'estado'], name='sales_venta_sucursa_dc620a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'creada'], name='sales_venta_sucursa_65fd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='sales_venta_estado_4c997e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['creada'], name='sales_venta_creada_0d15f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='unique_open_sale_per_user'),
        ),
        migrations.AddIndex(
            model_name='ventaitem',
            index=models.Index(fields=['venta'], name='sales_venta_venta_i_01dc02_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaitem',
            index=models.Index(fields=['sku'], name='sales_venta_sku_1169a4_idx'),
        ),
    ]
