# Generated by Django 5.1.7 on 2026-08-06 15:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boveda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boveda', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Bóveda',
                'verbose_name_plural': 'Bóvedas',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.sucursal')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], db_index=True, default='BORRADOR', max_length=20)),
                ('cliente', models.CharField(blank=True, default='', max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='core.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.carrito')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='core.sucursal')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='sales.listaprecio')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventory.productovariante')),
            ],
            options={
                'ordering': ['variante'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO_CAJERO', 'Cerrado por cajero'), ('CERRADO_SUPERVISOR', 'Cerrado por supervisor'), ('AUDITADO', 'Auditado')], db_index=True, default='ABIERTO', max_length=30)),
                ('abierto_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('monto_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monto_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacion_cierre', models.TextField(blank=True, default='')),
                ('auditado_en', models.DateTimeField(blank=True, null=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_auditados_caja', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='sales.caja')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_turnos_caja', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_caja', to='core.sucursal')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_apertura_caja', to=settings.AUTH_USER_MODEL)),
                ('usuario_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_supervisados_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-abierto_en'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('VENTA', 'Venta'), ('RETIRO_BOVEDA', 'Retiro a bóveda'), ('INGRESO', 'Ingreso manual'), ('EGRESO', 'Egreso manual'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=30)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR')], max_length=20, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacion', models.TextField(blank=True, default='')),
                ('numero_secuencia', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('hash_anterior', models.CharField(default='GENESIS', editable=False, max_length=64)),
                ('hash_integridad', models.CharField(db_index=True, editable=False, max_length=64)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('caja', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sales.caja')),
                ('sucursal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='core.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sales.turnocaja')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BovedaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RETIRO_CAJA', 'Retiro desde caja'), ('INGRESO_EXTERNO', 'Ingreso externo'), ('EGRESO_BOVEDA', 'Egreso de bóveda'), ('AJUSTE', 'Ajuste de bóveda')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacion', models.TextField(blank=True, default='')),
                ('numero_secuencia', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('hash_anterior', models.CharField(default='GENESIS', editable=False, max_length=64)),
                ('hash_integridad', models.CharField(db_index=True, editable=False, max_length=64)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('boveda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sales.boveda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_boveda', to=settings.AUTH_USER_MODEL)),
                ('movimiento_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_boveda', to='sales.cajamovimiento')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_boveda', to='sales.turnocaja')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArqueoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_contado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('APROBADO', 'Aprobado por supervisor'), ('ANULADO', 'Anulado')], db_index=True, default='REGISTRADO', max_length=20)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_realizados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='sales.turnocaja')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCajaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('desasignado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ajuste_redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.DateTimeField(blank=True, null=True)),
                ('anulada', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='referencia_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='sales.venta'),
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, default='', max_length=300)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('talla', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_tela', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArqueoDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='sales.arqueoturno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('arqueo', 'denominacion'), name='unique_denominacion_por_arqueo'), models.CheckConstraint(condition=models.Q(('denominacion__gt', 0)), name='arqueo_denominacion_positiva')],
            },
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['sucursal', 'activa'], name='sales_caja_sucursa_828b7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='unique_caja_codigo_por_sucursal'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['uuid'], name='sales_carri_uuid_3492f1_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario'], name='sales_carri_usuario_0eb1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['sucursal'], name='sales_carri_sucursa_066fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario', 'sucursal', 'estado'], name='sales_carri_usuario_caa7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='carritoitem',
            index=models.Index(fields=['carrito'], name='sales_carri_carrito_7cadd4_idx'),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['sucursal', 'activa'], name='sales_lista_sucursa_49d1b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='listaprecio',
            constraint=models.UniqueConstraint(fields=('sucursal', 'tipo_venta'), name='unique_lista_por_sucursal_tipo'),
        ),
        migrations.AddIndex(
            model_name='preciovariante',
            index=models.Index(fields=['lista'], name='sales_preci_lista_i_254c05_idx'),
        ),
        migrations.AddIndex(
            model_name='preciovariante',
            index=models.Index(fields=['variante'], name='sales_preci_variant_517596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preciovariante',
            unique_together={('variante', 'lista')},
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['sucursal', 'estado'], name='sales_turno_sucursa_e2d643_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['usuario_apertura', 'estado'], name='sales_turno_usuario_bd0f99_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['caja', 'abierto_en'], name='sales_turno_caja_id_2d2dd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('caja',), name='unique_turno_abierto_por_caja'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('usuario_apertura',), name='unique_turno_abierto_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto_inicial__gte', 0)), name='turno_monto_inicial_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto_esperado__gte', 0)), name='turno_monto_esperado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto_real__gte', 0)), name='turno_monto_real_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='bovedamovimiento',
            index=models.Index(fields=['boveda', 'numero_secuencia'], name='sales_boved_boveda__f18a27_idx'),
        ),
        migrations.AddIndex(
            model_name='bovedamovimiento',
            index=models.Index(fields=['boveda', 'creado_en'], name='sales_boved_boveda__225168_idx'),
        ),
        migrations.AddIndex(
            model_name='bovedamovimiento',
            index=models.Index(fields=['turno', 'creado_en'], name='sales_boved_turno_i_b70ef6_idx'),
        ),
        migrations.AddConstraint(
            model_name='bovedamovimiento',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='movimiento_boveda_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='bovedamovimiento',
            constraint=models.UniqueConstraint(fields=('boveda', 'numero_secuencia'), name='unique_movimiento_boveda_numero'),
        ),
        migrations.AddIndex(
            model_name='arqueoturno',
            index=models.Index(fields=['turno', 'creado_en'], name='sales_arque_turno_i_4cb1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='arqueoturno',
            index=models.Index(fields=['estado', 'creado_en'], name='sales_arque_estado_3aad3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='arqueoturno',
            constraint=models.CheckConstraint(condition=models.Q(('monto_esperado__gte', 0)), name='arqueo_monto_esperado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='arqueoturno',
            constraint=models.CheckConstraint(condition=models.Q(('total_contado__gte', 0)), name='arqueo_total_contado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='arqueoturno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'REGISTRADO')), fields=('turno',), name='unique_arqueo_registrado_por_turno'),
        ),
        migrations.AddIndex(
            model_name='turnocajausuario',
            index=models.Index(fields=['activo'], name='sales_turno_activo_4f2676_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnocajausuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('turno', 'usuario'), name='unique_usuario_activo_por_turno'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['uuid'], name='sales_venta_uuid_afd636_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'estado'], name='sales_venta_sucursa_dc620a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'creada'], name='sales_venta_sucursa_65fd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='sales_venta_estado_4c997e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['creada'], name='sales_venta_creada_0d15f5_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['turno', 'tipo'], name='sales_cajam_turno_i_5f2bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['turno', 'numero_secuencia'], name='sales_cajam_turno_i_d17ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['sucursal', 'creado_en'], name='sales_cajam_sucursa_b3330c_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['caja', 'creado_en'], name='sales_cajam_caja_id_a8d48d_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['referencia_venta'], name='sales_cajam_referen_2ed9fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0), models.Q(('monto', 0), ('tipo', 'APERTURA')), _connector='OR'), name='movimiento_caja_monto_valido'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(fields=('turno', 'numero_secuencia'), name='unique_movimiento_numero_por_turno'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'VENTA')), fields=('referencia_venta', 'medio_pago'), name='unique_movimiento_venta_por_medio'),
        ),
        migrations.AddIndex(
            model_name='ventaitem',
            index=models.Index(fields=['venta'], name='sales_venta_venta_i_01dc02_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaitem',
            index=models.Index(fields=['sku'], name='sales_venta_sku_1169a4_idx'),
        ),
    ]
