# Generated by Django 6.0.2 on 2026-02-23 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_mayorista', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total_contado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='sales.arqueoturno')),
            ],
        ),
        migrations.CreateModel(
            name='Boveda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boveda', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='sales.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventory.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO_CAJERO', 'Cerrado por Cajero'), ('CERRADO_SUPERVISOR', 'Cerrado por Supervisor'), ('AUDITADO', 'Auditado')], default='ABIERTO', max_length=30)),
                ('abierto_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='sales.caja')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arqueoturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='sales.turnocaja'),
        ),
        migrations.CreateModel(
            name='TurnoCajaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('desasignado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.DateTimeField(blank=True, null=True)),
                ('anulada', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('RETIRO_BOVEDA', 'Retiro a Bóveda'), ('INGRESO', 'Ingreso Manual'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=30)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR')], max_length=20, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hash_integridad', models.CharField(editable=False, max_length=64)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sales.turnocaja')),
                ('referencia_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_iva_aplicada', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('tipo_iva_aplicado', models.CharField(blank=True, max_length=20)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='unique_caja_codigo_por_sucursal'),
        ),
        migrations.AddIndex(
            model_name='precioproducto',
            index=models.Index(fields=['producto', 'lista'], name='sales_preci_product_7f3121_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precioproducto',
            unique_together={('producto', 'lista')},
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('caja',), name='unique_turno_abierto_por_caja'),
        ),
        migrations.AddConstraint(
            model_name='turnocajausuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('turno', 'usuario'), name='unique_usuario_activo_por_turno'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'estado'], name='sales_venta_sucursa_dc620a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'creada'], name='sales_venta_sucursa_65fd3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='unique_open_sale_per_user'),
        ),
    ]
