# Generated by Django 6.0.2 on 2026-02-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sucursal_lista_precio_default'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprecio',
            name='es_mayorista',
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='tipo_venta',
            field=models.CharField(blank=True, choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='listaprecio',
            constraint=models.UniqueConstraint(fields=('sucursal', 'tipo_venta'), name='unique_lista_por_sucursal_tipo'),
        ),
    ]
