# Generated by Django 5.1.7 on 2026-08-19 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_prenda', models.CharField(choices=[('APTA', 'Apta para la venta'), ('DANADA', 'Dañada / no apta para la venta')], max_length=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_modificado', models.BooleanField(default=False)),
                ('motivo_precio', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.AlterField(
            model_name='cajamovimiento',
            name='tipo',
            field=models.CharField(choices=[('APERTURA', 'Apertura'), ('VENTA', 'Venta'), ('CAMBIO', 'Cobro por cambio'), ('RETIRO_BOVEDA', 'Retiro a bóveda'), ('INGRESO', 'Ingreso manual'), ('EGRESO', 'Egreso manual'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=30),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('referencia_externa', models.CharField(blank=True, default='', help_text='Factura, nota o referencia opcional proporcionada por el cliente.', max_length=100)),
                ('tipo_venta', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=20)),
                ('tipo', models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('CAMBIO', 'Cambio de prenda')], max_length=20)),
                ('motivo', models.TextField()),
                ('permite_reembolso', models.BooleanField(default=False)),
                ('medio_reembolso', models.CharField(blank=True, default='', max_length=20)),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_entregado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_reembolsado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_no_reembolsado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='core.sucursal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='sales.turnocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='sales.venta')),
            ],
            options={
                'ordering': ['-creada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CambioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_entregados', to='sales.devolucion')),
            ],
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='referencia_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='sales.devolucion'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['referencia_devolucion'], name='sales_cajam_referen_c540cc_idx'),
        ),
        migrations.AddField(
            model_name='devoluciondetalle',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_devueltos', to='sales.devolucion'),
        ),
        migrations.AddField(
            model_name='devoluciondetalle',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante'),
        ),
        migrations.AddField(
            model_name='devoluciondetalle',
            name='venta_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='sales.ventaitem'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['sucursal', 'creada'], name='sales_devol_sucursa_ee73b7_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['venta', 'creada'], name='sales_devol_venta_i_72c550_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['turno'], name='sales_devol_turno_i_919399_idx'),
        ),
        migrations.AddConstraint(
            model_name='devoluciondetalle',
            constraint=models.UniqueConstraint(fields=('devolucion', 'venta_item'), name='unique_item_por_devolucion'),
        ),
    ]
