# Generated by Django 6.0.2 on 2026-02-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sucursal_lista_precio_default'),
        ('sales', '0002_remove_listaprecio_es_mayorista_listaprecio_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ajuste_redondeo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='tipo_venta',
            field=models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], max_length=20),
        ),
    ]
