# Generated by Django 5.1.7 on 2026-07-27 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_venta_cliente_venta_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
