# Generated by Django 5.1.7 on 2026-08-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_devoluciondetalle_alter_cajamovimiento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='tipo_venta',
            field=models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='MAYORISTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='tipo_venta',
            field=models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='MAYORISTA', max_length=20),
        ),
    ]
