# Generated by Django 5.1.7 on 2026-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_carrito_tipo_venta_alter_devolucion_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiodetalle',
            name='motivo_precio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cambiodetalle',
            name='precio_modificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='MAYORISTA', max_length=20),
        ),
    ]
