# Generated by Django 5.1.7 on 2026-07-27 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_sucursal_empresa'),
        ('sales', '0005_alter_venta_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venta',
            name='unique_open_sale_per_user',
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['uuid'], name='sales_venta_uuid_afd636_idx'),
        ),
    ]
