# Generated by Django 5.1.7 on 2026-07-27 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_venta_unique_open_sale_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
