# Generated by Django 5.1.7 on 2026-08-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cliente', models.CharField(choices=[('DETAL', 'Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
