# Generated by Django 6.0.2 on 2026-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMIN_SUCURSAL', 'Administrador de Sucursal'), ('CAJERO', 'Cajero'), ('INVENTARIO', 'Inventario')], max_length=20)),
            ],
        ),
    ]
