# Generated by Django 5.1.7 on 2026-08-08 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMIN_SUCURSAL', 'Administrador de sucursal'), ('SUPERVISOR', 'Supervisor de caja'), ('CAJERO', 'Cajero'), ('INVENTARIO', 'Inventario')], default='CAJERO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['sucursal', 'role'], name='accounts_us_sucursa_5c4f2d_idx'),
        ),
    ]
