# Generated by Django 5.1.7 on 2026-08-06 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(blank=True, max_length=250)),
                ('nit', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='SistemaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalado', models.BooleanField(default=False)),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('version_instalacion', models.CharField(default='1.0', max_length=20)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa')),
            ],
        ),
    ]
