# Generated by Django 5.1.7 on 2026-07-21 21:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_color_nombre_lower')],
            },
        ),
        migrations.CreateModel(
            name='ProduccionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumo_unitario', models.DecimalField(decimal_places=6, max_digits=12)),
                ('total_prendas', models.IntegerField()),
                ('merma', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_unitario_real', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('ejecutado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_producto_base_lower')],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('producto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventory.productobase')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('ANULACION', 'Anulación'), ('AJUSTE_ENTRADA', 'Ajuste entrada'), ('AJUSTE_SALIDA', 'Ajuste salida'), ('TRASLADO', 'Traslado'), ('DANADO', 'Dañado'), ('MERMA', 'Merma'), ('CONSUMO_INTERNO', 'Consumo interno'), ('DEVOLUCION_CLIENTE', 'Devolución cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución proveedor'), ('PRODUCCION', 'Producción'), ('INICIAL', 'Inventario inicial')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_post_movimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
            ],
        ),
        migrations.CreateModel(
            name='RolloTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_por_metro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('CONSUMIDO', 'Consumido')], default='DISPONIBLE', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('consumo_unitario', models.DecimalField(decimal_places=6, max_digits=12)),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=14)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.produccionlote')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventory.rollotela')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoRollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('CONSUMO', 'Consumo'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_post', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rollotela')),
            ],
        ),
        migrations.CreateModel(
            name='CorteRollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_consumidos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollos', to='inventory.produccionlote')),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rollotela')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_talla_nombre_lower')],
            },
        ),
        migrations.AddField(
            model_name='productovariante',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.talla'),
        ),
        migrations.CreateModel(
            name='TipoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_tela_nombre_lower')],
            },
        ),
        migrations.AddField(
            model_name='rollotela',
            name='tipo_tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tipotela'),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='tipo_tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tipotela'),
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('COMPLETO', 'Traslado completo'), ('SALIDA', 'Salida entre sucursales'), ('ENTRADA', 'Entrada entre sucursales'), ('AJUSTE_ENTRADA', 'Ajuste entrada'), ('AJUSTE_SALIDA', 'Ajuste salida'), ('DANADO', 'Producto dañado'), ('MERMA', 'Merma'), ('CONSUMO_INTERNO', 'Consumo interno'), ('DEVOLUCION_CLIENTE', 'Devolución cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución proveedor'), ('INICIAL', 'Carga inventario inicial')], default='COMPLETO', max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='core.sucursal')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_enviados', to=settings.AUTH_USER_MODEL)),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='core.sucursal')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TrasladoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.traslado')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.sucursal')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.productovariante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variante', 'sucursal'), name='unique_stock_variante_sucursal')],
            },
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['sku'], name='inventory_p_sku_14b172_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['codigo_barras'], name='inventory_p_codigo__a32a4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto_base', 'tipo_tela', 'color', 'talla')},
        ),
        migrations.AddIndex(
            model_name='traslado',
            index=models.Index(fields=['estado'], name='inventory_t_estado_e0eedf_idx'),
        ),
        migrations.AddIndex(
            model_name='traslado',
            index=models.Index(fields=['tipo'], name='inventory_t_tipo_1b147e_idx'),
        ),
        migrations.AddIndex(
            model_name='traslado',
            index=models.Index(fields=['numero'], name='inventory_t_numero_3f4041_idx'),
        ),
        migrations.AddIndex(
            model_name='traslado',
            index=models.Index(fields=['creado'], name='inventory_t_creado_7004ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trasladodetalle',
            unique_together={('traslado', 'variante')},
        ),
    ]
