# Generated by Django 6.0.2 on 2026-02-23 19:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tipo_iva', models.CharField(choices=[('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('NO_SUJETO', 'No sujeto')], default='GRAVADO', max_length=20)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('incluye_iva', models.BooleanField(default=True)),
                ('controla_stock', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='inventory_p_nombre_f7a701_idx'), models.Index(fields=['codigo_barras'], name='inventory_p_codigo__07ebb3_idx'), models.Index(fields=['activo'], name='inventory_p_activo_96a939_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste'), ('TRASLADO', 'Traslado')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['producto', 'sucursal'], name='inventory_m_product_c2c8fa_idx'), models.Index(fields=['tipo'], name='inventory_m_tipo_59c909_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.sucursal')),
            ],
            options={
                'indexes': [models.Index(fields=['producto', 'sucursal'], name='inventory_s_product_6831c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('producto', 'sucursal'), name='unique_stock_producto_sucursal')],
            },
        ),
    ]
