# Generated by Django 5.1.7 on 2026-03-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollotela',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingresoproduccion',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ordencorte'),
        ),
        migrations.CreateModel(
            name='ProduccionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumo_unitario', models.DecimalField(decimal_places=6, max_digits=12)),
                ('total_prendas', models.IntegerField()),
                ('ejecutado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rollotela')),
                ('tipo_tela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tipotela')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('producto_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productobase')),
                ('tipo_tela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tipotela')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.produccionlote')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ejecutado', models.BooleanField(default=False)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='core.sucursal')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.traslado')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productovariante')),
            ],
        ),
    ]
