# Generated by Django 5.1.7 on 2026-08-21 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CORTE', 'Corte'), ('CONFECCION', 'Confección')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperarioProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, default='', max_length=30)),
                ('especialidad', models.CharField(choices=[('CORTADOR', 'Cortador'), ('COSTURERA', 'Costurera'), ('AMBOS', 'Corte y confección')], default='AMBOS', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='produccionlote',
            options={'ordering': ['-creado', '-id']},
        ),
        migrations.AddField(
            model_name='produccionlote',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_CONFECCION', 'Pendiente de confección'), ('EN_CONFECCION', 'En confección'), ('FINALIZADO', 'Finalizado e ingresado a inventario')], db_index=True, default='PENDIENTE_CONFECCION', max_length=30),
        ),
        migrations.AlterField(
            model_name='producciondetalle',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producciondetalle',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producciondetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='produccionlote',
            index=models.Index(fields=['sucursal', 'estado'], name='inventory_p_sucursa_815938_idx'),
        ),
        migrations.AddField(
            model_name='operacionproduccion',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='inventory.producciondetalle'),
        ),
        migrations.AddField(
            model_name='operacionproduccion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_produccion_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operarioproduccion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operarios_produccion', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='operacionproduccion',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='inventory.operarioproduccion'),
        ),
        migrations.AddIndex(
            model_name='operarioproduccion',
            index=models.Index(fields=['sucursal', 'activo'], name='inventory_o_sucursa_31065d_idx'),
        ),
        migrations.AddIndex(
            model_name='operarioproduccion',
            index=models.Index(fields=['especialidad', 'activo'], name='inventory_o_especia_6cb68a_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionproduccion',
            index=models.Index(fields=['detalle', 'tipo'], name='inventory_o_detalle_2f1ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionproduccion',
            index=models.Index(fields=['operario', 'creado'], name='inventory_o_operari_ca1f99_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionproduccion',
            index=models.Index(fields=['tipo', 'creado'], name='inventory_o_tipo_5d3ab1_idx'),
        ),
    ]
