# Generated by Django 5.1.7 on 2026-06-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteRollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_consumidos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='produccionlote',
            name='inventory_p_referen_c94d5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='produccionlote',
            name='inventory_p_creado_f1330c_idx',
        ),
        migrations.RemoveField(
            model_name='produccionlote',
            name='rollo',
        ),
        migrations.AddField(
            model_name='corterollo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollos', to='inventory.produccionlote'),
        ),
        migrations.AddField(
            model_name='corterollo',
            name='rollo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rollotela'),
        ),
    ]
