# Generated by Django 5.1.7 on 2026-06-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_corterollo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciondetalle',
            name='rollo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventory.rollotela'),
        ),
    ]
