# Generated by Django 5.1.7 on 2026-04-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0003_alter_movimientostock_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionlote',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.sucursal'),
            preserve_default=False,
        ),
    ]
